# appium1.yml
server:
  port: 4723
  use-drivers:
    - xcuitest
  default-capabilities:
    wdaLocalPort: 8100
    wdaLaunchTimeout: 360000
    usePreinstalledWDA: true
    prebuiltWDAPath: Users/runner/Library/Developer/Xcode/DerivedData/WebDriverAgent-dtmoeonrefnxsncuficthanbldlc/Build/Products/WebDriverAgentRunner_iphonesimulator17.5-arm64.xctestrun
