# appium1.yml
server:
  port: 4723
  use-drivers:
    - xcuitest
  default-capabilities:
    wdaLocalPort: 8100
    wdaLaunchTimeout: 360000
    usePreinstalledWDA: true
    updatedWDABundleId: com.appium.WebDriverAgentRunner
