name: iOS Simulator Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-ios-simulator-tests:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Xcode and iOS Simulator
        run: |
          sudo xcode-select --switch /Applications/Xcode.app

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      # - name: Cache npm global packages
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.npm-global
      #     key: ${{ runner.os }}-npm-global-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-npm-global-
      # - name: Set npm global packages path
      #   run: |
      #     echo "NPM_CONFIG_PREFIX=~/.npm-global" >> $GITHUB_ENV
      #     echo "$HOME/.npm-global/bin" >> $GITHUB_PATH
      - name: Start Appium Server
        run: |
          npm install -g appium@next
          appium driver install xcuitest

      - run: appium driver list

      # - run: which appium
      # - run: ls -la /usr/local/bin
      # - run: sudo find / -name "WebDriverAgent.xcodeproj" 2>/dev/null
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: "3.x"

      # - name: Cache Python packages
      #   uses: actions/cache@v3
      #   with:
      #     # Cache location for pip
      #     path: ~/.cache/pip
      #     # Generate a unique key based on OS, Python version, and requirements.txt
      #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      #     # Use a partial key to restore similar caches if an exact match isn't found
      #     restore-keys: |
      #       ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # - run: npm install -g appium-webdriveragent
      - name: Download Appium dmg file
        run: |
          curl -L -o Appium.dmg https://github.com/appium/appium-desktop/releases/download/v1.21.0/Appium-mac-1.21.0.dmg

      - name: Mount the DMG file
        run: |
          hdiutil attach Appium.dmg

      # - name: List Volumes for Debugging
      #   run: |
      #     ls /Volumes/Appium

      - name: Copy Appium to Applications
        run: |
          # Adjust path based on actual volume name after listing volumes
          cp -R "/Volumes/Appium 1.21.0/Appium.app" /Applications/

      - name: Unmount the DMG file
        run: |
          hdiutil detach "/Volumes/Appium 1.21.0" || hdiutil detach "/Volumes/Appium*"

      - run: xcrun simctl create arm-app com.apple.CoreSimulator.SimDeviceType.iPhone-14 com.apple.CoreSimulator.SimRuntime.iOS-17-2

      - run: |
          cp -R ./appium-webdriveragent/* /Users/runner/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent
          cd  /Users/runner/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent
          pwd
          xcodebuild  -project WebDriverAgent.xcodeproj  \
          -scheme WebDriverAgentRunner \
          -destination 'platform=iOS Simulator,name=arm-app,OS=17.2'
          appium --base-path=/wd/hub -p 4723 &

      - name: Run the test
        run: |
          robot testcases/ios.robot

      - run: ls -l
